"""Write access_submission/fig_per_action.tex from experiments/robustness.json.

Grouped dot-and-interval plot: one group per action, one point per model with its 95%
vignette-cluster bootstrap interval (B=5000). Replaces the slopegraph, whose lines implied an
order among unordered action categories and carried no uncertainty.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import panel_config as pc  # FMA_PANEL=v3 -> read robustness_v3.json, write srep_submission/fig_per_action_v3.tex

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
data = json.load(open(pc.out_path("robustness", "json"), encoding="utf-8"))
models = data["item1_per_model_action_floors"]["models"]

ACTIONS = [("escalate_icu", "ICU escalation"), ("any_opioid", "Any opioid"), ("referral", "Referral"),
           ("high_acuity", "High acuity"), ("admit", "Admission"), ("cs_caution", "CS caution$^\\ast$" if pc.V3 else "CS caution")]
MODELS = [("A", "haiku-4.5", "cHaiku", "*"), ("B", "sonnet", "cSonnet", "square*"),
          ("C", "llama3.1:8b", "cLlama", "triangle*"), ("D", "mistral:7b", "cMistral", "diamond*"),
          ("E", "qwen3:4b", "cQwen", "pentagon*"), ("F", "phi3:mini", "cPhi", "otimes*")]
OFF = [-0.30, -0.18, -0.06, 0.06, 0.18, 0.30]

plots = []
for (mid, name, col, mark), off in zip(MODELS, OFF):
    rows = []
    for ai, (akey, _) in enumerate(ACTIONS, 1):
        a = models[mid]["actions"][akey]
        lo, hi = a["ci"]["B=5000"]
        f = a["floor"]
        rows.append("%.2f %.4f %.4f %.4f" % (ai + off, f, hi - f, f - lo))
    plots.append(r"""\addplot[only marks, mark=%s, mark size=1.9pt, color=%s,
  mark options={fill=%s, draw=%s!70!black, line width=0.3pt},
  error bars/.cd, y dir=both, y explicit, error bar style={%s, line width=0.7pt},
  error mark options={%s, mark size=1.4pt, rotate=90}]
  table[x=x, y=y, y error plus=ep, y error minus=em] {
x y ep em
%s
};
\addlegendentry{%s}""" % (mark, col, col, col, col, col, "\n".join(rows), name))

tex = r"""\documentclass[tikz,border=2pt]{standalone}
\usepackage{amsmath,amssymb}
\usepackage{xcolor}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usetikzlibrary{plotmarks}
%% Generated by harness/scripts/gen_fig_per_action.py from experiments/robustness%s.json.
\definecolor{cQwen}{HTML}{2A78D6}
\definecolor{cSonnet}{HTML}{EB6834}
\definecolor{cHaiku}{HTML}{1BAF7A}
\definecolor{cMistral}{HTML}{EDA100}
\definecolor{cLlama}{HTML}{E87BA4}
\definecolor{cPhi}{HTML}{008300}
\definecolor{inkMuted}{HTML}{52514E}
\definecolor{inkFaint}{HTML}{898781}
\begin{document}
\begin{tikzpicture}
\begin{axis}[
  width=16cm, height=6.6cm,
  xmin=0.5, xmax=6.5, ymin=-0.01, ymax=0.52,
  xtick={1,2,3,4,5,6},
  xticklabels={%s},
  x tick label style={font=\small, text=inkMuted},
  ytick={0,0.1,0.2,0.3,0.4,0.5},
  scaled y ticks=false,
  yticklabel style={/pgf/number format/fixed, /pgf/number format/fixed zerofill, /pgf/number format/precision=1, font=\small, text=inkMuted},
  ylabel={Per-action instability floor (proportion)},
  label style={font=\small, text=inkMuted},
  axis x line*=bottom, axis y line*=left,
  axis line style={inkFaint}, tick style={inkFaint},
  ymajorgrids=true, grid style={inkFaint!25},
  extra x ticks={1.5,2.5,3.5,4.5,5.5}, extra x tick labels={},
  extra x tick style={grid=major, major grid style={inkFaint!45, dashed}, tick style={draw=none}},
  legend style={font=\footnotesize, at={(0.5,1.02)}, anchor=south, legend columns=6, draw=none,
    /tikz/every even column/.append style={column sep=6pt}},
  legend cell align=left,
]
%s
\end{axis}
\end{tikzpicture}
\end{document}
""" % (pc.SUFFIX, ",".join(l for _, l in ACTIONS), "\n".join(plots))
# Plain-decimal data table appended as comments, so every per-action rate the manuscript
# reports remains checkable against this source by verify_paper_numbers.py.
lines = ["% ---------------------------------------------------------------------------------",
         "% Per-action, per-model floors (3 d.p.); row = action, col = model",
         "% (A haiku-4.5, B sonnet, C llama3.1:8b, D mistral:7b, E qwen3:4b, F phi3:mini)",
         "%",
         "% action          " + "  ".join("%-7s" % m for m, *_ in MODELS)]
for akey, _ in ACTIONS:
    lines.append("%% %-15s " % akey + "  ".join(
        "%.3f  " % models[m]["actions"][akey]["floor"] for m, *_ in MODELS))
tex = tex + "\n".join(lines) + "\n"
# The old panel keeps writing access_submission/fig_per_action.tex; v3 never touches it.
out = (os.path.join(ROOT, "srep_submission", "fig_per_action_v3.tex") if pc.V3
       else os.path.join(ROOT, "access_submission", "fig_per_action.tex"))
open(out, "w", encoding="utf-8", newline="\n").write(tex)
print("wrote", out)
