"""Write the v3 floor-by-model figures from experiments/robustness_v3.json.

    FMA_PANEL=v3 python gen_fig_floor_by_model.py

Writes, next to the originals and without touching them or anything in access_submission/:
    srep_submission/fig_floor_by_model_v3.tex            pooled floor, six actions
    srep_submission/fig_floor_by_model_v3_5action.tex    pooled floor, five actions (no cs_caution)

Both use the paired vignette-cluster bootstrap intervals (B=5000, seed 42) that robustness.py
writes, one dot per model, sorted ascending by the plotted floor.
"""
from __future__ import annotations

import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import panel_config as pc  # noqa: E402

if not pc.V3:
    raise SystemExit("run with FMA_PANEL=v3 (this script only writes the _v3 figures)")

ROOT = pc.ROOT
data = json.load(open(pc.out_path("robustness", "json"), encoding="utf-8"))
NAMES = {"A": "haiku-4.5", "B": "sonnet", "C": "llama3.1:8b", "D": "mistral:7b",
         "E": "qwen3:4b", "F": "phi3:mini"}
COLORS = {"A": "cHaiku", "B": "cSonnet", "C": "cLlama", "D": "cMistral", "E": "cQwen", "F": "cPhi"}

HEAD = r"""\documentclass[tikz,border=2pt]{standalone}
\usepackage{amsmath,amssymb}
\usepackage{xcolor}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
%% Generated by harness/scripts/gen_fig_floor_by_model.py from experiments/robustness_v3.json
%% (FMA_PANEL=v3). %(what)s
\definecolor{cQwen}{HTML}{2A78D6}
\definecolor{cSonnet}{HTML}{EB6834}
\definecolor{cHaiku}{HTML}{1BAF7A}
\definecolor{cMistral}{HTML}{EDA100}
\definecolor{cLlama}{HTML}{E87BA4}
\definecolor{cPhi}{HTML}{008300}
\definecolor{inkMuted}{HTML}{52514E}
\definecolor{inkFaint}{HTML}{898781}
\begin{document}
\begin{tikzpicture}
\begin{axis}[
  width=8.2cm, height=6.2cm,
  xlabel={%(xlabel)s},
  xmin=0, xmax=%(xmax).2f,
  x tick label style={font=\scriptsize},
  xtick={%(xticks)s},
  scaled x ticks=false,
  xticklabel style={/pgf/number format/fixed, /pgf/number format/fixed zerofill,
    /pgf/number format/precision=2},
  ytick=data,
  symbolic y coords={%(ycoords)s},
  y dir=reverse,
  axis y line*=left,
  axis x line*=bottom,
  ymajorgrids=false,
  xmajorgrids=true,
  grid style={inkFaint!35},
  axis line style={inkFaint},
  tick style={inkFaint},
  tick label style={font=\small, text=inkMuted},
  label style={font=\small, text=inkMuted},
  enlarge y limits=0.15,
  clip=false,
]
\addplot [
  only marks,
  mark=none,
  error bars/.cd,
    x dir=both,
    x explicit,
    error bar style={inkFaint, line width=0.9pt},
    error mark options={mark size=3pt, line width=0.9pt, rotate=90, inkFaint},
] table [x=floor, y=model, x error plus=errplus, x error minus=errminus] {
model        floor  errplus errminus
%(table)s
};
%(dots)s
%(labels)s
\end{axis}
\end{tikzpicture}
\end{document}
"""


def write(rows, name, xlabel, what):
    """rows: list of (lab, floor, lo, hi). Sorted ascending by floor."""
    rows = sorted(rows, key=lambda r: r[1])
    xmax = max(0.05, math.ceil((max(r[3] for r in rows) + 0.035) / 0.05) * 0.05)
    xticks = ",".join("%.2f" % (0.05 * i) for i in range(int(round(xmax / 0.05)) + 1))
    table = "\n".join("%-12s %.3f  %.3f   %.3f" % (NAMES[l], f, hi - f, f - lo) for l, f, lo, hi in rows)
    dots = "\n".join(
        "\\addplot [only marks, mark=*, mark size=3.4pt,\n  mark options={fill=%s, draw=white, line width=0.8pt}] "
        "coordinates {(%.3f,%s)};" % (COLORS[l], f, NAMES[l]) for l, f, lo, hi in rows)
    labels = "\n".join(
        "\\node[anchor=west, font=\\scriptsize, text=inkMuted, xshift=4pt] at (axis cs:%.3f,%s) {$%.3f$};"
        % (hi, NAMES[l], f) for l, f, lo, hi in rows)
    tex = HEAD % {"what": what, "xlabel": xlabel, "xmax": xmax, "xticks": xticks,
                  "ycoords": ",".join(NAMES[r[0]] for r in rows), "table": table,
                  "dots": dots, "labels": labels}
    out = os.path.join(ROOT, "srep_submission", name)
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(tex)
    print("wrote", out)
    for l, f, lo, hi in rows:
        print("  %-12s %.3f [%.3f, %.3f]" % (NAMES[l], f, lo, hi))


pooled = data["item1_per_model_action_floors"]["models"]
rows6 = [(l, pooled[l]["pooled"]["floor"], *pooled[l]["pooled"]["ci"]["B=5000"]) for l in NAMES]
write(rows6, "fig_floor_by_model_v3.tex", "Pooled instability floor (proportion)",
      "Pooled over the six binary actions.")

five = data["item9_five_action_analysis"]["models"]
rows5 = [(l, five[l]["floor_5action"], *five[l]["ci_5action_B5000"]) for l in NAMES]
write(rows5, "fig_floor_by_model_v3_5action.tex",
      "Pooled instability floor, five actions (proportion)",
      "Pooled over five actions: cs\\_caution (no operational criteria) excluded.")
