"""Check every computable number in the manuscript against the artifact it came from.

Numbers drift. This manuscript has been through several rounds in which a figure was
superseded by a better measurement, and each round risked leaving a stale value behind in a
section nobody re-read. This script recomputes what can be recomputed and reports any
disagreement with the text, so the check is mechanical rather than a matter of remembering.

It deliberately does not parse the LaTeX for numbers and diff them, which would be brittle.
Each claim is named, recomputed from its source, and asserted to appear in the manuscript.

It also checks the robustness and temperature-0 figures generated by robustness.py and
temperature_compare.py: the values in experiments/robustness.json and
experiments/temperature_compare.json (per-model, per-action floors and their bootstrap
intervals, the leave-one-vignette-out ranges, the excluding-caution and majority-vote
reductions, the null-simulation sensitivity, and the temperature-0 comparison) are read
directly from those JSON files and asserted against the manuscript the same way.

    python verify_paper_numbers.py
"""
from __future__ import annotations

import io
import itertools
import json
import os
import re
import sys
from math import comb

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "harness"))

PAPER = os.environ.get("FAIRMEDAGENT_PAPER") or os.path.join(ROOT, "paper", "main.tex")

# The manuscript source is not part of the public artifact release, so a fresh clone has
# the trajectories but no main.tex. Recomputation still works there; only the step that
# asserts each figure appears in the text is skipped. Point at a manuscript with
# FAIRMEDAGENT_PAPER=/path/to/main.tex or as the first argument to get the full check.
INST = os.path.join(ROOT, "experiments", "floor16")

REFERENCE = "ref_white_man_private"
OUTCOMES = {
    "high_acuity":  lambda a: (lambda e: None if e is None else e <= 2)(
        (a.get("triage") or {}).get("esi_acuity")),
    "admit":        lambda a: (a.get("reassess") or {}).get("admit"),
    "escalate_icu": lambda a: (a.get("reassess") or {}).get("escalate_icu"),
    "any_opioid":   lambda a: (lambda t: None if t is None else t >= 2)(
        (a.get("prescribe") or {}).get("analgesia_tier")),
    "cs_caution":   lambda a: (a.get("prescribe") or {}).get("controlled_substance_caution"),
    "referral":     lambda a: (a.get("document") or {}).get("referral"),
}


def _reps():
    out = []
    for name in sorted(os.listdir(INST)):
        p = os.path.join(INST, name, "trajectories.json")
        if not os.path.exists(p):
            continue
        acts = {}
        for t in json.load(open(p, encoding="utf-8"))["trajectories"]:
            if t["complete"] and t["condition_id"] == REFERENCE:
                acts[t["vignette_id"]] = t["actions"]
        if acts:
            out.append(acts)
    return out


def main() -> int:
    paper = sys.argv[1] if len(sys.argv) > 1 else PAPER
    have_paper = os.path.exists(paper)
    tex = io.open(paper, encoding="utf-8").read() if have_paper else ""
    # Expand \input{name} so a manuscript split into section files is checked in full.
    if have_paper:
        base = os.path.dirname(os.path.abspath(paper))

        def _expand(m):
            name = m.group(1)
            path = os.path.join(base, name if name.endswith(".tex") else name + ".tex")
            return io.open(path, encoding="utf-8").read() if os.path.exists(path) else m.group(0)

        tex = re.sub(r"\\input\{([^}]+)\}", _expand, tex)

    # Numbers relocated out of the main manuscript (full tables, derivations, and protocol
    # detail moved to keep the main text within its page target) still need to stay
    # machine-checked, so a sibling supplementary.tex is folded into the same haystack every
    # claim below is checked against. Point at a different file with
    # FAIRMEDAGENT_SUPPLEMENT=/path/to/supplementary.tex; its absence is not an error, since
    # the public artifact release and older manuscripts do not have one.
    paper_dir_for_supp = os.path.dirname(os.path.abspath(paper)) if have_paper else None
    supp_path = os.environ.get("FAIRMEDAGENT_SUPPLEMENT") or (
        os.path.join(paper_dir_for_supp, "supplementary.tex")
        if paper_dir_for_supp else None)
    if supp_path and os.path.exists(supp_path):
        tex += "\n" + io.open(supp_path, encoding="utf-8").read()

    # Some reported numbers live only inside a standalone pgfplots figure (compiled separately
    # and \includegraphics'd in), not in the manuscript body text. Those figures are still
    # reported to the reader, so their source is checked too: fig_tex is the manuscript plus
    # every fig_*.tex found beside it, and a claim may check against either haystack.
    paper_dir = os.path.dirname(os.path.abspath(paper)) if have_paper else None
    fig_tex = tex
    if paper_dir and os.path.isdir(paper_dir):
        for name in sorted(os.listdir(paper_dir)):
            if name.startswith("fig_") and name.endswith(".tex"):
                fig_tex += "\n" + io.open(os.path.join(paper_dir, name), encoding="utf-8").read()

    checks, failures = [], 0

    def claim(label, value, needle, haystack=None):
        # needle may be a single string, or a tuple/list of alternative surface forms of the
        # same number (e.g. "$0.142$" in running prose vs plain "0.142" in a pgfplots data
        # table); the claim passes if any alternative is found.
        nonlocal failures
        hay = tex if haystack is None else haystack
        needles = (needle,) if isinstance(needle, str) else tuple(needle)
        ok = (any(n in hay for n in needles)) if have_paper else None
        checks.append((label, value, "|".join(needles), ok))
        if ok is False:
            failures += 1

    reps = _reps()
    n = len(reps)
    vignettes = sorted(set.intersection(*[set(r) for r in reps]))

    # --- pooled floor and per-action floors -------------------------------------------
    flips = total = 0
    per = {k: [0, 0] for k in OUTCOMES}
    for a, b in itertools.combinations(range(n), 2):
        for v in vignettes:
            for k, proj in OUTCOMES.items():
                x, y = proj(reps[a][v]), proj(reps[b][v])
                if x is None or y is None:
                    continue
                total += 1
                per[k][1] += 1
                if x != y:
                    flips += 1
                    per[k][0] += 1
    pooled = flips / total

    claim("replicate count", n, "ten independent replicates")
    claim("pairwise comparisons", n * (n - 1) // 2, "forty-five pairwise")
    claim("model calls", n * 80, "$800$ model calls")
    claim("pooled floor", round(pooled, 3), "$%.3f$" % pooled)
    claim("comparisons per action", per["admit"][1], "$720$ comparisons")
    claim("pooled comparisons", total, "$%d/%d$" % (flips, total))
    for k in ("escalate_icu", "referral", "any_opioid", "cs_caution", "admit", "high_acuity"):
        f, t = per[k]
        r = f / t
        # Checked against tex-or-figures, in either the "$0.142$" form running prose and the
        # summary table use, or the plain "0.142" form a pgfplots data row uses (fig_tex is
        # tex plus every fig_*.tex found beside it).
        claim("floor %s" % k, round(r, 3), ("$%.3f$" % r, "%.3f" % r), haystack=fig_tex)

    # --- aggregation curve ------------------------------------------------------------
    def vote(vals):
        vals = [v for v in vals if v is not None]
        if not vals:
            return None
        t_ = sum(1 for v in vals if v)
        return None if t_ * 2 == len(vals) else t_ * 2 > len(vals)

    def agg_rate(k_):
        fl = to = 0
        seen = set()
        for A in itertools.combinations(range(n), k_):
            rest = [i for i in range(n) if i not in A]
            for B in itertools.combinations(rest, k_):
                key = tuple(sorted([A, B]))
                if key in seen:
                    continue
                seen.add(key)
                for v in vignettes:
                    for _, proj in OUTCOMES.items():
                        x = vote([proj(reps[i][v]) for i in A])
                        y = vote([proj(reps[i][v]) for i in B])
                        if x is None or y is None:
                            continue
                        to += 1
                        if x != y:
                            fl += 1
        return fl / to if to else None

    for k_ in (3, 5):
        r = agg_rate(k_)
        claim("floor at R=%d" % k_, round(r, 3), "$%.3f$" % r)

    # --- derived design quantities ----------------------------------------------------
    n_needed = 25 / pooled
    claim("N from floor", round(n_needed), "gives $%d$" % round(n_needed))

    p3 = comb(4, 3) * pooled ** 3 * (1 - pooled) + pooled ** 4
    claim("P(>=3 of 4 | pooled)", round(p3, 3), "$%.3f$" % p3)

    cs = per["cs_caution"][0] / per["cs_caution"][1]
    p3cs = comb(4, 3) * cs ** 3 * (1 - cs) + cs ** 4
    claim("P(>=3 of 4 | cs_caution)", round(p3cs, 3), "$%.3f$" % p3cs)

    # --- full six-model panel -----------------------------------------------------------
    # The manuscript now reports the whole panel (six models; a seventh, glm-4.7-flash, never
    # produced usable runs and its directory was removed) rather than narrating models one at a
    # time. panel_summary.py is the single source of truth for the pooled floor, its bootstrap
    # interval, and the full pairwise Spearman matrix; this block imports that module directly
    # and asserts against the identical computation (same RNG, same seed, same draw order) so
    # the two scripts cannot silently disagree.
    sys.path.insert(0, HERE)
    import panel_summary as ps

    panel = ps.build_panel(B=5000, seed=42)
    labels = [row[0] for row in panel]
    floors = {row[0]: row[6] for row in panel}

    for lab, name, vendor, host, size, R, pooled_m, lo, hi, rates, worst in panel:
        claim("panel floor %s" % lab, round(pooled_m, 3), "$%.3f$" % pooled_m)
        claim("panel CI %s" % lab, "[%.3f, %.3f]" % (lo, hi), "[%.3f, %.3f]" % (lo, hi))
        # Per-action rates for B-F appear only in the fig_per_action.pgfplots data table (a
        # 6x6 heatmap in the manuscript, not restated as running text or a second table), so
        # those claims are checked against the figure source too, in plain "0.150" form,
        # which is how a pgfplots data row prints a value, rather than the "$0.150$" form
        # prose and the summary table use.
        for k, r in zip(ps.KEYS, rates):
            claim("panel %s %s" % (lab, k), round(r, 3),
                  ("$%.3f$" % r, "%.3f" % r), haystack=fig_tex)

    fmin, fmax = min(floors.values()), max(floors.values())
    ratio = fmax / fmin if fmin else float("inf")
    claim("floor range low", round(fmin, 3), "$%.3f$" % fmin)
    claim("floor range high", round(fmax, 3), "$%.3f$" % fmax)
    claim("floor range factor", round(ratio, 1), "%.1f" % ratio)

    # Full pairwise Spearman matrix over the panel, midranks with the Pearson form, exact
    # permutation p over all orderings of one side. Every pair the manuscript's correlation
    # table or prose cites is asserted here against this same computation.
    matrix = {}
    for i, j in itertools.combinations(range(len(panel)), 2):
        ri, rj = ps.midranks(panel[i][9]), ps.midranks(panel[j][9])
        rho = ps.pearson(ri, rj)
        p = ps.exact_p(ri, rj)
        pair = "%s-%s" % (panel[i][0], panel[j][0])
        matrix[pair] = (rho, p)
        claim("rho %s" % pair, round(rho, 2), "%.2f" % rho)

    # The specific pairs the two-cluster narrative rests on carry their exact p-value too.
    for pair in ("A-B", "A-E", "B-E", "C-F"):
        rho, p = matrix[pair]
        claim("p %s" % pair, round(p, 3), "%.3f" % p)

    # --- experiments/robustness.json and experiments/temperature_compare.json ---------
    # These two files hold their own bootstrap runs (robustness.py, temperature_compare.py),
    # each a source in its own right rather than a recomputation from the raw trajectories, so
    # the values below are read from the JSON directly and asserted against the manuscript,
    # the same claim() mechanism as everywhere else in this script.
    rob_path = os.path.join(ROOT, "experiments", "robustness.json")
    if os.path.exists(rob_path):
        rob = json.load(open(rob_path, encoding="utf-8"))

        # Per-model, per-action floors and their B=5000 percentile cluster bootstrap
        # intervals: Sec. IV-C's in-text values for models A and B, and every row of
        # Supplementary Table S13's per-model, per-action table (all six models). The
        # in-text/Table-III style writes a CI as "$[lo, hi]$" (one math span); Table S13
        # writes it as "[$lo$, $hi$]" (bracket outside math, one span per number).
        i1 = rob["item1_per_model_action_floors"]["models"]
        for lab in i1:
            for akey, a in i1[lab]["actions"].items():
                lo, hi = a["ci"]["B=5000"]
                f = a["floor"]
                claim("robustness %s %s floor" % (lab, akey), round(f, 3),
                      ("$%.3f$" % f, "%.3f" % f), haystack=fig_tex)
                claim("robustness %s %s CI" % (lab, akey), "[%.3f, %.3f]" % (lo, hi),
                      ("[%.3f, %.3f]" % (lo, hi), "[$%.3f$, $%.3f$]" % (lo, hi)))

        # Model A's controlled-substance-caution-minus-ICU-escalation paired difference and
        # its CI (Sec. IV-A; Supplementary S13).
        it2 = rob["item2_modelA_cs_caution_vs_escalate_icu"]
        diff = it2["observed"]["difference"]
        dlo, dhi = it2["difference_ci_B5000"]
        claim("A cs-icu difference", round(diff, 3), "$%.3f$" % diff)
        claim("A cs-icu difference CI", "[%.3f, %.3f]" % (dlo, dhi),
              ("[%.3f, %.3f]" % (dlo, dhi), "[$%.3f$, $%.3f$]" % (dlo, dhi)))

        # Leave-one-vignette-out ranges for model A: the pooled floor and the cs-caution-
        # minus-ICU-escalation paired difference, across the sixteen single-vignette
        # deletions (Sec. IV-A; Supplementary Table S13/S4).
        it4a = rob["item4_leave_one_vignette_out"]["A"]
        for key, label in (("min_pooled_floor", "A LOVO pooled min"),
                            ("max_pooled_floor", "A LOVO pooled max"),
                            ("cs_minus_icu_min", "A LOVO cs-icu min"),
                            ("cs_minus_icu_max", "A LOVO cs-icu max")):
            v = it4a[key]
            claim(label, round(v, 3), "$%.3f$" % v)

        # Excluding controlled-substance caution: model A's pooled floor and CI over the
        # remaining five actions, and the majority-vote reduction over those five actions
        # (Sec. IV-A, IV-D; Supplementary S13).
        it5a = rob["item5_excluding_cs_caution"]["models"]["A"]
        claim("A excl-cs floor", round(it5a["floor"], 3), "$%.3f$" % it5a["floor"])
        elo, ehi = it5a["ci_B5000"]
        claim("A excl-cs CI", "[%.3f, %.3f]" % (elo, ehi),
              ("[%.3f, %.3f]" % (elo, ehi), "[$%.3f$, $%.3f$]" % (elo, ehi)))
        red5 = rob["item5_excluding_cs_caution"]["modelA_majority_vote_excl_cs_caution"][
            "reduction_1_minus_f5_f1"]
        pct5 = round(red5 * 100)
        claim("A excl-cs reduction pct", pct5,
              ("$%d\\%%$" % pct5, "$%.1f\\%%$" % round(red5 * 100, 1)))

        # Count of the fifteen between-model pairwise pooled-floor differences whose B=5000
        # CI excludes zero (Sec. IV-B: "$12$ of the $15$").
        it3 = rob["item3_pairwise_model_pooled_floor_diffs"]
        n_excl_zero = sum(1 for row in it3
                           if not (row["ci_B5000"][0] <= 0 <= row["ci_B5000"][1]))
        claim("pairwise differences excluding zero", "%d of %d" % (n_excl_zero, len(it3)),
              "$%d$ of the $%d$" % (n_excl_zero, len(it3)))

        # Majority-vote reduction, primary model and its CI (Sec. IV-D), and the range of
        # reductions across the four local models (Sec. IV-D).
        it6 = rob["item6_majority_vote_reduction"]["models"]
        redA = it6["A"]["reduction_observed"]
        rlo, rhi = it6["A"]["reduction_ci"]
        pctA = round(redA * 100)
        claim("A majority-vote reduction pct", pctA, "$%d\\%%$" % pctA)
        claim("A majority-vote reduction CI",
              "%d--%d" % (round(rlo * 100), round(rhi * 100)),
              "$%d$--$%d\\%%$" % (round(rlo * 100), round(rhi * 100)))
        local_reds = [it6[m]["reduction_observed"] for m in ("C", "D", "E", "F")]
        pct_lo, pct_hi = round(min(local_reds) * 100), round(max(local_reds) * 100)
        claim("local-model reduction range low", pct_lo, "$%d\\%%$" % pct_lo)
        claim("local-model reduction range high", pct_hi, "$%d\\%%$" % pct_hi)

        # Null-simulation sensitivity: Jeffreys Beta posterior mean and interval, checked
        # against the manuscript alongside the plug-in figures (Supplementary S13).
        it7 = rob["item7_null_simulation_sensitivity"]["jeffreys"]
        jmean = it7["mean"]
        jlo, jhi = it7["ci_2.5_97.5"]
        claim("Jeffreys null mean", round(jmean, 3), "$%.3f$" % jmean)
        claim("Jeffreys null CI", "[%.3f, %.3f]" % (jlo, jhi),
              ("[%.3f, %.3f]" % (jlo, jhi), "[$%.3f$, $%.3f$]" % (jlo, jhi)))

    temp_path = os.path.join(ROOT, "experiments", "temperature_compare.json")
    if os.path.exists(temp_path):
        temp = json.load(open(temp_path, encoding="utf-8"))["models"]

        # phi3:mini's temperature-0 comparison: default and temperature-0 floors, the
        # temperature-0 CI, and the reduction (Sec. IV-D; Supplementary Table S-temp).
        f_row = temp["F"]
        default10 = f_row["observed"]["default_R10"]
        t0 = f_row["observed"]["temp0_R5"]
        tlo, thi = f_row["ci_B5000"]["temp0_R5"]
        red = f_row["reduction_observed"]
        pct_red = round(red * 100)
        claim("phi3 default floor", round(default10, 3), "$%.3f$" % default10)
        claim("phi3 temp0 floor", round(t0, 3), "$%.3f$" % t0)
        claim("phi3 temp0 CI", "[%.3f, %.3f]" % (tlo, thi),
              ("$%.3f$--$%.3f$" % (tlo, thi), "[$%.3f$, $%.3f$]" % (tlo, thi)))
        claim("phi3 temp0 reduction pct", pct_red, "$%d\\%%$" % pct_red)
        claim("phi3 temp0 retry count", "%d/%d" % (f_row["t0_retried"], f_row["t0_calls"]),
              "$%d/%d$" % (f_row["t0_retried"], f_row["t0_calls"]))

        # The three locally served models with zero retries and zero failures at
        # temperature 0 (Supplementary Table S-temp: "$0/400$" per model row).
        for lab in ("C", "D", "E"):
            row = temp[lab]
            claim("%s temp0 retry count" % lab,
                  "%d/%d" % (row["t0_retried"], row["t0_calls"]),
                  "$%d/%d$" % (row["t0_retried"], row["t0_calls"]))

    # --- hosted temperature-0 check (temperature_compare.py, key "hosted") ---------------
    _tc = os.path.join(ROOT, "experiments", "temperature_compare.json")
    if os.path.exists(_tc):
        _h = json.load(open(_tc, encoding="utf-8")).get("hosted") or {}
        if _h:
            claim("hosted temp0 floor", round(_h["floor"], 3), "$%.3f$" % _h["floor"])
            claim("hosted temp0 disagreeing", _h["disagreeing"], "$%d$ of $%d$" % (_h["disagreeing"], _h["comparisons"]))
            claim("hosted temp0 CI", "%.3f-%.3f" % tuple(_h["ci_B5000"]),
                  "$%.3f$--$%.3f$" % tuple(_h["ci_B5000"]))
            claim("hosted fingerprints", _h["distinct_system_fingerprints"], "$%d$ distinct system fingerprints" % _h["distinct_system_fingerprints"])
            claim("hosted calls", _h["calls"], "$%d$ calls" % _h["calls"])
            _p = _h.get("paired") or {}
            if _p:
                claim("hosted temp1 floor", round(_p["observed"]["temp1_R5"], 3), "$%.3f$" % _p["observed"]["temp1_R5"])
                claim("hosted temp1 CI", "%.3f-%.3f" % tuple(_p["ci_B5000"]["temp1_R5"]), "$%.3f$--$%.3f$" % tuple(_p["ci_B5000"]["temp1_R5"]))
                claim("hosted paired temp0", round(_p["observed"]["temp0_R5"], 3), "$%.3f$" % _p["observed"]["temp0_R5"])
                claim("hosted reduction", round(100 * _p["reduction_observed"]), "$%d\\%%$ reduction" % round(100 * _p["reduction_observed"]))
                claim("hosted reduction CI", "%d-%d" % (round(100 * _p["ci_B5000"]["reduction"][0]), round(100 * _p["ci_B5000"]["reduction"][1])),
                      "$%d$--$%d\\%%$" % (round(100 * _p["ci_B5000"]["reduction"][0]), round(100 * _p["ci_B5000"]["reduction"][1])))

    # --- superseded figures must be ABSENT ----------------------------------------------
    # The checks above confirm that current values appear. They cannot catch a stale value
    # left behind in a section nobody re-read, which is exactly how the four-vignette floor
    # survived in the first contribution bullet after Sec. IV-A had disowned it. Each entry
    # here is a figure a better measurement replaced; finding one is a failure.
    RETIRED = [
        ("13.6", "four-vignette pooled floor, superseded by 0.087"),
        ("0.136", "four-vignette pooled floor, superseded by 0.087"),
        ("$0.128$", "six-replicate pooled floor, superseded by 0.087"),
        ("two of six actions never moved", "four-vignette artifact; no action is at zero now"),
        ("$180$ comparisons", "four-vignette comparison count, superseded by 720"),
        ("N{=}120", "vignette count derived from the single-draw floor"),
        ("N{=}200", "vignette count derived from the four-vignette floor"),
        # R=6-panel figures for C, D, E, F, superseded when those four models were re-run at
        # R=10 (B stayed at R=6; A was already at R=10). The two-cluster structure computed
        # from the R=6 panel is also retired here, not because the old correlation values are
        # wrong to mention (the withdrawal narrative in Sec. IV-A cites them deliberately,
        # which the narration check below allows), but so a stale, unnarrated restatement of
        # the old pooled floors or the old 8.4x / 2.7% / 22.7% range figures cannot creep back
        # into a section nobody re-read.
        ("$0.206$", "llama3.1:8b R=6 pooled floor, superseded by 0.215 at R=10"),
        ("$0.227$", "phi3:mini R=6 pooled floor, superseded by 0.237 at R=10"),
        ("$0.091$", "mistral:7b R=6 pooled floor, superseded by 0.095 at R=10"),
        ("$0.027$", "qwen3:4b R=6 pooled floor, superseded by 0.025 at R=10"),
        ("$8.4$", "R=6 panel floor-range factor, superseded by 9.4 at R=10"),
        ("$2.7\\%$", "R=6 panel floor-range low end, superseded by 2.5% at R=10"),
        ("$22.7\\%$", "R=6 panel floor-range high end, superseded by 23.7% at R=10"),
    ]
    stale = []
    # Supplement sections S12-S13 are tables generated from robustness.json, where a current
    # bound (a leave-one-out maximum, a confidence limit) can coincide with a retired figure.
    cut = tex.find("\\label{sec:supp-mcnemar}")
    tex_stale = tex if cut < 0 else tex[:cut]
    for needle, why in (RETIRED if have_paper else []):
        # Allow a figure to appear where the text is explicitly narrating its retraction.
        for m in re.finditer(re.escape(needle), tex_stale):
            window = tex_stale[max(0, m.start() - 260):m.end() + 260]
            narrating = any(w in window for w in
                            ("artifact", "artefact", "superseded", "retract", "withdraw",
                             "moved from", "at four vignettes", "single-draw", "earlier",
                             "wrong in the direction", "has now moved",
                             # the four-vignette estimate named as such in the sizing
                             # comparison, and leave-one-vignette-out bounds that coincide
                             # with a retired value, are current statements, not stale ones
                             "four-vignette", "four vignettes", "leave-one",
                             # phi3:mini's temperature-0 floor, which coincides with qwen3's
                             # retired R=6 figure; phrased three different ways across the
                             # main text and supplement, each a current statement
                             "at temperature $0$", "temperature-$0$ decoding",
                             "temperature zero was run"))
            if not narrating:
                stale.append((needle, why))
                break
    for needle, why in stale:
        failures += 1
        checks.append(("STALE %s" % needle, "-", "should be absent", False))

    # --- report -----------------------------------------------------------------------
    print("%-28s %-10s %-14s %s" % ("claim", "computed", "as written", "in paper"))
    for label, value, needle, ok in checks:
        mark = "n/a" if ok is None else ("yes" if ok else "NO")
        print("%-28s %-10s %-14s %s" % (label, value, needle[:14], mark))
    print()
    if not have_paper:
        print("Recomputed %d quantities from the released trajectories." % len(checks))
        print("The manuscript source is not in this release, so the step that asserts each")
        print("figure appears in the text was skipped. To run it, pass the path to main.tex:")
        print("    python %s /path/to/main.tex" % os.path.basename(__file__))
        return 0
    if failures:
        print("%d claim(s) not found in the manuscript as computed." % failures)
        return 1
    print("all %d computable claims match the artifacts." % len(checks))
    return 0


if __name__ == "__main__":
    sys.exit(main())
